### ISSUE TITLE
The ArgMax circuit doesn't work with MP-SPDZ

### ISSUE THREAD

**Issue by curryrasul** [namnc/circom-2-arithc#77]
The compiled [ArgMax](https://github.com/namnc/circom-mp-spdz/blob/ml_tests/ml_tests/ArgMax/ArgMax.circom) circuit doesn't work with MP-SPDZ, because of the errors with constants:
```bash
/MP-SPDZ ((704049e1)) ~> PLAYERS=2 Scripts/compile-run.py -E semi circuit -M          Wed Jun 26 12:47:40 2024
Default bit length for compilation: 64
Default security parameter for compilation: 40
Compiling file Programs/Source/circuit.mpc
Traceback (most recent call last):
  File "/MP-SPDZ/Scripts/compile-run.py", line 14, in <module>
    prog = compiler.compile_file()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/MP-SPDZ/Scripts/../Compiler/compilerLib.py", line 452, in compile_file
    exec(compile(infile.read(), infile.name, "exec"), self.VARS)
  File "Programs/Source/circuit.mpc", line 6, in <module>
    wires[10] = wires[9] - wires[7]
                ~~~~~~~~~^~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'sint'
```

**Comment by namnc** [comment]
I think I fixed this with https://github.com/namnc/circom-2-arithc/commit/6e280217b1662350fd550f55ffb42b89fbfe3bda. BUT up to @curryrasul to confirm.

The issue should be due to 2 things:

The naming of a constant signal does not take into account multiple instances of a template, e.g. Switcher.const_signal_0 appears multiple times with different signal ids --> naming could be more robust with differentiation between instances, e.g. Switcher_0.const_signal_0 and Switcher_1.const_signal_1
This leads to merging based on constant signal names failed as now every signal has the same name are merged into one even though it should be all of them --> merging can be more robust, e.g. by appending signal id at the end we can keep every const signal, e.g. Switcher.const_signal_0_18, Switcher.const_signal_0_24. --> ALSO what I have done inside the fix.

**Comment by curryrasul** [comment]
Yes @namnc , thanks a lot, it works now!
